project_name: Default
working_dir: "."
cmd:
- python main.py
provisioning:
  gpu_type: a10g
  gpu_count: 4
  cpu_count: 48
  ram: 192
teamcity:
  url: https://mlops.staging.sandbox.teamcity.aws.intellij.net
  build_conf_id: Dbce089802aa4ab4a7c3ebdd4928443b_JetTrain
env:
  variables: {}
  python:
    pip:
      requirements_path: requirements.txt
    version: 3.11.10
  secrets:
    variables: {}
    ssh_keys: []
  aws:
    sync_config: false
    sync_credentials: false
    sync_cache: false
project_sync:
  local:
    root: "."
    storage_name: Cadence Storage
    uri: ""
    exclude:
    - C:/Users/sinan/PycharmProjects/LunarLander-DQN-Sample/.venv/**
    include: []
    sync_back: false
    snapshots: true
    storage_type: DEFAULT
inputs: []
outputs:
- type: OUTPUT
  storage_name: Cadence Storage
  uri: data/b0260e5f-562c-4b71-90f7-b781deb43c7a/snapshots/sinantaskinlar/2024-12-14T03-54-47Z_8de88590-627c-4434-9522-f70840b7d4d8/outputs/
  path: "."
  acceleration: false
  storage_type: DEFAULT
mounts: []
storages: []
description: test
